"""add_rank_msg_settings

Revision ID: 7a0d4c9d5e3f
Revises: fb23df35c71b
Create Date: 2026-07-14 10:34:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0d4c9d5e3f'
down_revision: Union[str, None] = 'fb23df35c71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('rank_msg_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('guild_settings', sa.Column('rank_msg_template', sa.Text(), server_default="Congratulations {user}, you achieved the rank of {rank} on the {path} path!", nullable=False))
    op.add_column('guild_settings', sa.Column('rank_msg_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('guild_settings', sa.Column('rank_msg_embed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('guild_settings', sa.Column('rank_msg_image_url', sa.String(length=256), nullable=True))
    op.add_column('guild_settings', sa.Column('rank_msg_mention_user', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('guild_settings', sa.Column('rank_msg_mention_role_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'rank_msg_mention_role_id')
    op.drop_column('guild_settings', 'rank_msg_mention_user')
    op.drop_column('guild_settings', 'rank_msg_image_url')
    op.drop_column('guild_settings', 'rank_msg_embed')
    op.drop_column('guild_settings', 'rank_msg_channel_id')
    op.drop_column('guild_settings', 'rank_msg_template')
    op.drop_column('guild_settings', 'rank_msg_enabled')
    # ### end Alembic commands ###
